/*
** Automatically generated by CorePackageGenerator
*/

#ifndef COREPACKAGES_COMMANDS_VARIABLE_SETTYPE_H
#define COREPACKAGES_COMMANDS_VARIABLE_SETTYPE_H

#include <string>
#include <QString>

#include "dnai/corepackages/commands/icommanddata.h"
#include "Cerealizable/Tuple.hpp"
#include "dnai/enums/core/core.h"

using namespace Cerealization::Cerealizable;

namespace dnai
{
    using namespace enums::core;

    namespace corepackages
    {
        namespace variable
        {
            class SetType : public ICommandData, public Tuple<EntityID, EntityID>
            {
            public:
                SetType(EntityID p_variable, EntityID p_type) :
                    Tuple<EntityID, EntityID>(variable, type),
                    variable(p_variable), type(p_type)
                {

                }

                ~SetType() = default;

            public:
                static std::string EVENT()
                {
                    return "VARIABLE.SET_TYPE";
                }

            public:
                EntityID variable; EntityID type;
            };
        }
    }
}

#endif // COREPACKAGES_COMMANDS_VARIABLE_SETTYPE_H
