split_by_point
mkdir %APPVEYOR_BUILD_FOLDER%-build
cd %APPVEYOR_BUILD_FOLDER%-build
qmake -o %APPVEYOR_BUILD_FOLDER%-build -r -Wall -spec win32-msvc CONFIG+=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%/Gui "VERSION_MAJOR=%VERSION_MAJOR%" "VERSION_MINOR=%VERSION_MINOR%" "VERSION_BUILD=%VERSION_BUILD%" && jom qmake_all
jom
jom install