#!/bin/sh

#VARIABLES
dmg_path="./"
dmg_name="DNAI-Installer.dmg"
slug="installer"
#END

release_version=null

if [ "$1" == "--release" ]
  then
    if [ "$2" ]
	then
	release_version=$2
    fi
fi

if [ $release_version == null ]
then
    exit 1
fi

echo 'login :'
read login #admin
echo 'password :'
read password #dnai

token=$(curl -X POST https://api.preprod.dnai.io/signin -H 'authorization: Basic YWRtaW46ZG5haQ==' -H 'cache-control: no-cache' -H 'content-type: application/json' -H 'postman-token: b3f8b8c8-fe13-7b8e-7aa7-ca49752db305' -d "{ \"login\": \"$login\", \"password\": \"$password\"}" | jq -r '.token')

if [ $token == null ]
then
    echo "failed to get token"
    exit 2
fi

id=$(curl -X POST https://api.preprod.dnai.io/download/softwares/mac -H "authorization: Bearer $token" -H 'cache-control: no-cache' -H 'content-type: application/json' -H 'postman-token: 4ba51ed8-cd69-7ddc-4dcf-2e78d3675e1e' -d "{
      \"title\": \"Revision for $release_version\",
      \"description\": \"Generated by installer.sh on Mac.\",
      \"slug\": \"$slug\",
      \"currentVersion\": \"$release_version\"
}" | jq -r '._id')

id=$(curl -X PATCH https://api.preprod.dnai.io/download/softwares/mac/$slug -H "authorization: Bearer $token" -H 'cache-control: no-cache' -H 'content-type: application/json' -H 'postman-token: 4ba51ed8-cd69-7ddc-4dcf-2e78d3675e1e' -d "{
      \"title\": \"Revision for installer slug\",
      \"description\": \"Generated by installer.sh on Mac.\",
      \"slug\": \"$slug\",
      \"currentVersion\": \"$release_version\"
}" | jq -r '._id')


#requete vers PUT MISSING THE FILE
pwd

curl -X PUT --upload-file "$dmg_path$dmg_name"  https://api.preprod.dnai.io/download/softwares/mac/$slug/$release_version -H "authorization: Bearer $token" -H 'cache-control: no-cache' -H 'content-type: text/plain' -H 'postman-token: c8638d15-6169-9fb9-2bb3-6314e0d66b45'

exit 0